on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Initialize project
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm run test
